// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eknavqqqnxevntmkhmsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbmF2cXFxbnhldm50bWtobXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjA5MzcsImV4cCI6MjA2NTE5NjkzN30.yTiS__B1V4rKhvpn7M2ihbXr8Yt6YScKKQu3r7wXSCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);